### ISSUE TITLE
Backdrop

### ISSUE THREAD

**Issue by binjospookie** [GoogleChrome/dialog-polyfill#115]
I want to close the dialog by clicking on the backdrop. What should I do to reach this?

Code:
``` html
<html>
<head>
  <script src="dialog-polyfill.js"></script>
  <link rel="stylesheet" type="text/css" href="dialog-polyfill.css" />
  <style>
    dialog::backdrop {
      position: fixed;
      top: 0;
      left: 0;
      right: 0;
      bottom: 0;
      background-color: rgba(0, 0, 0, 0.8);
    }
  </style>
</head>
<body>
  <dialog>
    I'm a dialog!
    <form method="dialog">
      <button type="button">Close</button>
    </form>
  </dialog>
  <script>
    var dialog = document.querySelector('dialog');
    var close = dialog.querySelector('button');
    dialogPolyfill.registerDialog(dialog);
    dialog.showModal();
    close.onclick = function() {
      dialog.close();
    }
  </script>
</body>
</html

```

**Comment by samthor** [comment]
Firstly note that `::backdrop` doesn't support the polyfill, you'll also need `+ .backdrop` for that. The best practice needs two things-

* create a `div` that covers the entire dialog (`position: absolute; width: 100%; height: 100%;`), remembering to set the `dialog` to `position: relative` to contain it
* add a click handler to the dialog itself

If you see a click on the dialog, i.e. where the event's target is the dialog, you know it must be the backdrop. Otherwise, the event's target would have been the covering div.

**Comment by samthor** [comment]
Closing since this is not an issue.

**Comment by mreinstein** [comment]
a possible alternative approach that doesn't require div tag soup:

when the dialog is opened:
* attach a click event handler to the body, which takes the event target and traverses up the `parentNode`s. If a `<dialog>` element is one of the ancestors, close the dialog

when the dialog is closed:
* detach the body click event handler
