### ISSUE TITLE
including a page to <dialog>

### ISSUE THREAD

**Issue by mohsin25** [GoogleChrome/dialog-polyfill#46]
Can we include a page to <dialog>? We are using showModalDialog by adding a page from URL, can we do same here?

**Comment by mattto** [comment]
You cannot directly do that, as it's not part of the ```<dialog>``` spec. Dialog exists inside a document, it isn't a separate document like showModalDialog was. Maybe the best way would be to put an ```<iframe>``` in a ```<dialog>```.

**Comment by mohsin25** [comment]
Matto, thanks a lot for you reply. I have another confusion please help me in clearing it. Our clients use our application on Internet explorer and firefox. dialog tag is not supported on both as mentioned on w3schools. Some websites say dialog tag will not be the part of HTML 5 specification. Now I am confused should I use this polyfill? If in future these two browsers do not support dialog tag than where will I stand. Our application has around 1000 modal dialogs so what should I do?

**Comment by mattto** [comment]
The point of the polyfill is to allow you to use ```<dialog>``` in browsers that don't implement it. So today you can use ```<dialog>``` natively where available and then fallback to the polyfill for other browsers.

Ideally, you would never need the polyfill. Currently ```<dialog>``` is supported in Chrome and Opera but not other browsers. I've seen positive signals from other browsers but it's unknown when they will add support. For example, Firefox has a [bug](https://bugzilla.mozilla.org/show_bug.cgi?id=840640) you can follow; they've also have good [developer documentation](https://developer.mozilla.org/en-US/docs/Web/API/HTMLDialogElement).

The state of HTML specifications takes some time to explain. The short answer is yes, it is in the HTML spec. The longer answer is, the WHATWG HTML spec [has dialog] (https://html.spec.whatwg.org/multipage/forms.html#the-dialog-element), and the W3C HTML 5.1 spec also [has dialog](http://www.w3.org/TR/html51/semantics.html#the-dialog-element). The W3C decided to put it in HTML 5.1 rather than HTML 5 because of lack of browser support at the time.
