### ISSUE TITLE
Dialogs should only be centered when shown modally

### ISSUE THREAD

**Issue by samthor** [GoogleChrome/dialog-polyfill#52]
When dialogs are modal, they are put into the top layer. When they're not, they should be positioned using [normal alignment, as per the spec](http://www.w3.org/html/wg/drafts/html/master/semantics.html#normal-alignment).

Currently, we try to position them in the center no matter what.

Chrome's native implementation (as of M43) mostly does this. Dialogs shown normally are just positioned as per the user agent CSS. However, if a dialog is shown modally, closed, and then shown again, it's still centered: _this_ is a bug.

**Comment by samthor** [comment]
Fixed.

**Comment by Garbee** [comment]
I'm not sure which is newer exactly (since keeping up with specs is difficult) but the [Candidate Recommendation](http://www.w3.org/TR/2013/CR-html5-20130806/interactive-elements.html#set-up-the-default-static-position) of HTML5 shows that the dialog should only have *two* modes. This means normal dialogs should also get centered like modals from what I can tell.

Might be reading incorrectly or could just be outdated, but maybe something to look into again here.
