### ISSUE TITLE
Firefox - tab focus gets stuck on body

### ISSUE THREAD

**Issue by SystemParadox** [GoogleChrome/dialog-polyfill#85]
When focusing on an element outside a modal (i.e. with the tab key), the polyfill just tries to prevent the event and calls `blur()` on the target. There's a TODO note about focusing on browser chrome or the dialog itself depending on the tab direction.

The current behaviour appears to be sufficient for Chrome 45 and IE11 (at least for the cases I have tried), but on Firefox 35 the focus gets stuck on the `<body>`. Pressing tab tries to focus the next element in the body, but this is denied or blurred, and the focus ends up back on the `<body>`.

**Comment by samthor** [comment]
So note that Chrome doesn't use the polyfill: `dialog` is supported natively since M37.

I've had a bit of a go [over here](https://github.com/GoogleChrome/dialog-polyfill/compare/master...samthor:tab-direction). It's tricky though, but sort of reveals another bug: it's not easy to find the first (or last...) focusable element inside a `div`.

Some weird ideas-
* on some browsers, you can create a fake element and then a fake tab event, but that's ugly too (found while investigating `[inert-polyfill](https://github.com/GoogleChrome/inert-polyfill)`)
* hidden focusable divs inside `dialog`, used to do this, but it's confusing from a DOM point of view

I'll keep thinking.

**Comment by samthor** [comment]
I've fixed this for the before-`dialog` case (ignored the after for now).

**Comment by SystemParadox** [comment]
That's great. Thanks very much.
